config/routes.rb
Rails.application.routes.draw do
  resources :produks

end

app/models/produk.rb
class Produk < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/produks_controller.rb
class ProduksController < ApplicationController
  before_action :set_produk, only: [:show, :edit, :update, :destroy]

  # GET /produks
  # GET /produks.json
  def index
    @produks = Produk.all

     if params[:first_button]
      pdf = ProdukPdf.new(@produks)
      send_data pdf.render, filename: 'produk.pdf', type: 'application/pdf',disposition: 'inline'
     end

  end

  # GET /produks/1
  # GET /produks/1.json
  def show
  end

  # GET /produks/new
  def new
    @produk = Produk.new
  end

  # GET /produks/1/edit
  def edit
  end

  # POST /produks
  # POST /produks.json
  def create
    @produk = Produk.new(produk_params)

    respond_to do |format|
      if @produk.save
        format.html { redirect_to @produk, notice: 'Produk was successfully created.' }
        format.json { render :show, status: :created, location: @produk }
      else
        format.html { render :new }
        format.json { render json: @produk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produks/1
  # PATCH/PUT /produks/1.json
  def update
    respond_to do |format|
      if @produk.update(produk_params)
        format.html { redirect_to @produk, notice: 'Produk was successfully updated.' }
        format.json { render :show, status: :ok, location: @produk }
      else
        format.html { render :edit }
        format.json { render json: @produk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produks/1
  # DELETE /produks/1.json
  def destroy
    @produk.destroy
    respond_to do |format|
      format.html { redirect_to produks_url, notice: 'Produk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produk
      @produk = Produk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produk_params
      params.require(:produk).permit(:nama, :stok)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produks_helper.rb
module ProduksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Appprawn</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/produks/_form.html.erb
<%= form_for(@produk) do |f| %>
  <% if @produk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produk.errors.count, "error") %> prohibited this produk from being saved:</h2>

      <ul>
      <% @produk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nama %><br>
    <%= f.text_field :nama %>
  </div>
  <div class="field">
    <%= f.label :stok %><br>
    <%= f.number_field :stok %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/produks/edit.html.erb
<h1>Editing Produk</h1>

<%= render 'form' %>

<%= link_to 'Show', @produk %> |
<%= link_to 'Back', produks_path %>

app/views/produks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Produks</h1>
<br>
 
<%= link_to "cetak data produk",produks_path( :first_button => 'cetak'),:target=>'_blank' %>
 
<br>
<table>
  <thead>
    <tr>
      <th>Nama</th>
      <th>Stok</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produks.each do |produk| %>
      <tr>
        <td><%= produk.nama %></td>
        <td><%= produk.stok %></td>
        <td><%= link_to 'Show', produk %></td>
        <td><%= link_to 'Edit', edit_produk_path(produk) %></td>
        <td><%= link_to 'Destroy', produk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 
 
<br>
<%= link_to 'New Produk', new_produk_path %>

app/views/produks/new.html.erb
<h1>New Produk</h1>

<%= render 'form' %>

<%= link_to 'Back', produks_path %>

app/views/produks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nama:</strong>
  <%= @produk.nama %>
</p>

<p>
  <strong>Stok:</strong>
  <%= @produk.stok %>
</p>

<%= link_to 'Edit', edit_produk_path(@produk) %> |
<%= link_to 'Back', produks_path %>